### PR TITLE
feat: scenes can't be viewed through collisions

### PR DESCRIPTION
**Pull request by Scullyy**
Also changed PlayerPedId() to cache.ped as you are using ox_lib

### CODE REVIEW

**Comment by iSentrie** [comment]
still needs a bit of work so it wouldn't disappear 


https://github.com/SamShanks1/fivem-scenes/assets/29688478/27cbf98a-4b16-4cfb-bc7e-9ae1da034268

**Comment by Scullyy** [comment]
image

Can't repro this, the ped is also ignored in the 8th parameter

**Review by JnKTechstuff — CHANGES_REQUESTED** [review]
What makes this untenable is the flags used. The current shape-test flag will hide the text over anything. A bit less restricting to flag `1` would achieve what you want without hiding the text behind random stuff.

```lua
	local _, hit, _, _, entityHit = GetShapeTestResult(StartShapeTestRay(coords.x, coords.y, coords.z, sceneCoords.x, sceneCoords.y, sceneCoords.z, 1, cache.ped, 4))
```

**Comment by Scullyy** [comment]
> What makes this untenable is the flags used. The current shape-test flag will hide the text over anything. A bit less restricting to flag `1` would achieve what you want without hiding the text behind random stuff.
> 
> ```lua
> 	local _, hit, _, _, entityHit = GetShapeTestResult(StartShapeTestRay(coords.x, coords.y, coords.z, sceneCoords.x, sceneCoords.y, sceneCoords.z, 1, cache.ped, 4))
> ```

If something is in the way of the text you shouldn’t be able to see it at all.

**Pull request merged**
